# Generated by Django 2.0 on 2018-08-17 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_num', models.IntegerField(default=1)),
                ('step_num', models.IntegerField(default=1)),
                ('step_text', models.TextField()),
                ('step_note', models.TextField()),
                ('step_image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='document',
            name='hunter',
        ),
        migrations.RemoveField(
            model_name='document',
            name='step_text',
        ),
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='document',
            name='doc_num',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='document',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='last_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('rf', 'RF'), ('gui', 'GUI'), ('web', 'Web UI')], default='rf', max_length=3),
        ),
    ]
