# Generated by Django 2.0 on 2018-08-17 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_auto_20180817_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='step_nav',
            field=models.CharField(default='', max_length=250),
        ),
    ]
