# Generated by Django 2.0 on 2018-08-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_step_step_nav'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='doc_num',
        ),
        migrations.RemoveField(
            model_name='document',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='document',
            name='last_name',
        ),
        migrations.AddField(
            model_name='document',
            name='application',
            field=models.CharField(choices=[('jda', 'JDA/RP'), ('hj', 'Highjump'), ('sap', 'SAP'), ('o', 'Other')], default='jda', max_length=3),
        ),
    ]
