# Generated by Django 2.0 on 2018-09-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_auto_20180906_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='version',
            field=models.CharField(default='', max_length=10),
        ),
    ]
