# Generated by Django 2.0 on 2018-08-20 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0005_auto_20180820_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='doc_num',
            new_name='document_id',
        ),
    ]
