# Generated by Django 2.0 on 2018-08-20 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0006_auto_20180820_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='document_id',
        ),
        migrations.AddField(
            model_name='step',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
