# Generated by Django 2.0 on 2018-09-07 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0006_auto_20180906_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
        migrations.RemoveField(
            model_name='client',
            name='user',
        ),
        migrations.RemoveField(
            model_name='document',
            name='user',
        ),
    ]
