# Generated by Django 2.0 on 2018-08-22 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0007_auto_20180820_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='title',
        ),
        migrations.AddField(
            model_name='step',
            name='step_id',
            field=models.IntegerField(default=0),
        ),
    ]
