# Generated by Django 2.0 on 2018-08-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0008_auto_20180821_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='step_id',
        ),
        migrations.AddField(
            model_name='step',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
