# Generated by Django 2.0 on 2018-09-11 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0008_auto_20180911_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='navigation',
        ),
    ]
