# Generated by Django 2.0 on 2018-09-12 14:57

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0009_remove_step_navigation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\gjoyner\\Desktop\\sop\\static'), upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='step',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
