# Generated by Django 2.0 on 2018-08-22 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0009_auto_20180822_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='application',
            field=models.CharField(default='jda', max_length=3),
        ),
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(default='inventory', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='client',
            field=models.CharField(default='def', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(default='rf', max_length=3),
        ),
    ]
