# Generated by Django 2.0 on 2018-08-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0010_auto_20180822_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='application',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='client',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(default='', max_length=3),
        ),
    ]
