# Generated by Django 2.0 on 2018-08-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0011_auto_20180822_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='application',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(default='', max_length=20),
        ),
    ]
