# Generated by Django 2.0 on 2018-08-22 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('docs', '0011_auto_20180822_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='creator',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='application',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(default='', max_length=20),
        ),
    ]
