# Generated by Django 2.0 on 2018-08-22 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0012_auto_20180822_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='step_num',
            field=models.FloatField(default=1),
        ),
    ]
