# Generated by Django 2.0 on 2018-08-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0013_auto_20180822_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(default='', max_length=100)),
                ('category', models.CharField(default='', max_length=100)),
                ('title', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='document',
            name='category',
        ),
        migrations.RemoveField(
            model_name='document',
            name='client',
        ),
    ]
