# Generated by Django 2.0 on 2018-08-22 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0013_document_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='creator',
            field=models.ForeignKey(default='super', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
