# Generated by Django 2.0 on 2018-08-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0014_auto_20180823_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='title',
        ),
        migrations.AddField(
            model_name='document',
            name='folder_category',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='document',
            name='folder_client',
            field=models.IntegerField(default=1),
        ),
    ]
