# Generated by Django 2.0 on 2018-08-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0015_auto_20180823_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Folder',
            new_name='CategoryFolder',
        ),
    ]
