# Generated by Django 2.0 on 2018-08-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0016_auto_20180823_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='folder_category',
        ),
        migrations.RemoveField(
            model_name='document',
            name='folder_client',
        ),
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='document',
            name='client',
            field=models.CharField(default='', max_length=100),
        ),
    ]
