# Generated by Django 2.0 on 2018-08-22 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0018_auto_20180822_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='creator',
        ),
    ]
